export enum NAME_VALIDATION_CONSTANTS {
  MIN_LENGTH = 5,
  MAX_LENGTH = 256,
}

export enum PASSWORD_VALIDATION_CONSTANTS {
  MIN_LENGTH = 8,
  MIN_LOWERCASE_CHARACTERS = 1,
  MIN_UPPERCASE_CHARACTERS = 1,
  MIN_NUMBERS = 1,
  MIN_SYMBOLS = 1,
}
